[package]
name = "keytree"
version = "0.1.0"
authors = ["Dan Aloni <alonid@gmail.com>"]
edition = "2018"

[dependencies]
cairo-rs = "0.9"
calloop = "0.14"
calloop-wayland-source = "0.4"
config = "0.13.2"
dirs = "3"
image = "0.18.0"
lazy_static = "1.4"
log = "0.4"
pango = "0.9"
pangocairo = "0.10"
regex = "1.5"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
smithay-client-toolkit = { version = "0.21", features = ["calloop", "xkbcommon"] }
structopt = "0.3"
thiserror = "1"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
xkbcommon = "0.8"
